version: '3.8'

services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.28.4
    command: --host 0.0.0.0 --port 8080 --scheme http
    ports:
      - 8080:8080
      - 50051:50051
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    environment:
      IMAGE_INFERENCE_API: "http://i2v-neural:8080"
      # CLIP_INFERENCE_API: http://multi2vec-clip:8080
      QUERY_DEFAULTS_LIMIT: 5
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'img2vec-neural'
      ENABLE_MODULES: 'img2vec-neural'
      CLUSTER_HOSTNAME: 'node1'

  i2v-neural:
    image: cr.weaviate.io/semitechnologies/img2vec-pytorch:resnet50
    environment:
      ENABLE_CUDA: '0'

  # multi2vec-clip:
  #   image: cr.weaviate.io/semitechnologies/multi2vec-clip:sentence-transformers-clip-ViT-B-32-multilingual-v1
  #   environment:
  #     ENABLE_CUDA: 0  

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weaviate_app
    ports:
      - 6060:6060
    depends_on:
      - weaviate
      - i2v-neural
    volumes:
      - ./uploads:/uploads
      - ./.config:/.config
      - ./data:/data

volumes:
  weaviate_data:



    

