
name: Build and Push Docker Image to JFrog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Log into JFrog Docker Registry
        run: echo "${{ secrets.JFROG_PASSWORD }}" | docker login ${{ secrets.JFROG_URL }} -u ${{ secrets.JFROG_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t trialo3lkne.jfrog.io/weaviate-docker-local/demo-weaviate:latest .

      - name: Push Docker image to JFrog
        run: |
          docker push trialo3lkne.jfrog.io/weaviate-docker-local/demo-weaviate:latest

      - name: Collect build Metadata & Environment Info
        run: |
          jfrog rt  my-build ${{ github.run_number }}
          jfrog rt build-collect-env dress-review-build ${{ github.run_number }}

      - name: Publish Build Info to JFrog
        run: |
          jfrog rt build-publish dress-review-build ${{ github.run_number }}
        


