
name: Build and Push Docker Image to JFrog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Log into JFrog Docker Registry
        run: echo "${{ secrets.JFROG_PASSWORD }}" | docker login ${{ secrets.JFROG_URL }} -u ${{ secrets.JFROG_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
#docker build -t ${{ secrets.JFROG_URL }}/weaviate-docker-local/demoweaviate:latest .
          docker build -t https://trialo3lkne.jfrog.io/weaviate-docker-local/demoweaviate:latest .

      - name: Push Docker image to JFrog
        run: |
          docker push ${{ secrets.JFROG_URL }}/weaviate-docker-local/demoweaviate:latest
        


